// utils/bookCategories.js
export const bookCategories = [
    { key: "arts", label: "Arts & Photography" },
    { key: "biographies", label: "Biographies & Memoirs" },
    { key: "business", label: "Business & Money" },
    { key: "calendars", label: "Calendars" },
    { key: "children", label: "Children's Books" },
    { key: "christian", label: "Christian Books & Bibles" },
    { key: "comics", label: "Comics & Graphic Novels" },
    { key: "computers", label: "Computers & Technology" },
    { key: "cookbooks", label: "Cookbooks, Food & Wine" },
    { key: "crafts", label: "Crafts, Hobbies & Home" },
    { key: "education", label: "Education & Teaching" },
    { key: "engineering", label: "Engineering & Transportation" },
    { key: "health", label: "Health, Fitness & Dieting" },
    { key: "history", label: "History" },
    { key: "humor", label: "Humor & Entertainment" },
    { key: "law", label: "Law" },
    { key: "literature", label: "Literature & Fiction" },
    { key: "medical", label: "Medical Books" },
    { key: "mystery", label: "Mystery, Thriller & Suspense" },
    { key: "parenting", label: "Parenting & Relationships" },
    { key: "politics", label: "Politics & Social Sciences" },
    { key: "reference", label: "Reference" },
    { key: "religion", label: "Religion & Spirituality" },
    { key: "romance", label: "Romance" },
    { key: "science", label: "Science & Math" },
    { key: "scifi", label: "Science Fiction & Fantasy" },
    { key: "selfhelp", label: "Self-Help" },
    { key: "sports", label: "Sports & Outdoors" },
    { key: "teen", label: "Teen & Young Adult" },
    { key: "test-prep", label: "Test Preparation" },
    { key: "travel", label: "Travel" },
];