// utils/bookCategories.js
export const featuredCategories = [
    { key: "biographies", label: "Biographies & Memoirs" },
    { key: "business", label: "Business & Money" },
    // { key: "children", label: "Children's Books" },
    // { key: "christian", label: "Christian Books & Bibles" },
    { key: "computers", label: "Computers & Technology" },
    // { key: "cookbooks", label: "Cookbooks, Food & Wine" },
    // { key: "crafts", label: "Crafts, Hobbies & Home" },
    // { key: "education", label: "Education & Teaching" },
    // { key: "engineering", label: "Engineering & Transportation" },
    { key: "health", label: "Health, Fitness & Dieting" },
    // { key: "history", label: "History" },
    // { key: "law", label: "Law" },
    // { key: "literature", label: "Literature & Fiction" },
    { key: "medical", label: "Medical Books" },
    // { key: "parenting", label: "Parenting & Relationships" },
    // { key: "reference", label: "Reference" },
    // { key: "religion", label: "Religion & Spirituality" },
    // { key: "romance", label: "Romance" },
    { key: "science", label: "Science & Math" },
    // { key: "selfhelp", label: "Self-Help" },
    { key: "sports", label: "Sports & Outdoors" },
];